### ISSUE TITLE
minimumValue probably recalculated every time

### ISSUE THREAD

**Issue by peternlewis** [fastred/ReflectableEnum#8]
Wont _minimumValue typically be zero?  And therefore the 

if ( !_minimumValue ) { 

test will be true even when it has already been calculated, thus causing an recalculation each time.

I haven't actually tried ReflectableEnum - it looks cool, but I have my own solutions for the most part, sp I might be wrong.

**Comment by fastred** [comment]
Thanks for taking the time to point this out. Should be fixed now.
